docs: refactor environment variables document after encapsulation of environment varibles
frmscoe/docs pull request #152
Opened 2024-11-04 14:33 UTC by cshezi

# SPDX-License-Identifier: Apache-2.0

## What did we change?
Refactored docs page to reflect the new changes of encapsulating environment variables

## Why are we doing this?
To allow integrators to have easier time using the library

## How was it tested?
- [ ] Locally
- [ ] Development Environment
- [ ] Not needed, changes very basic
- [ ] Husky successfully run
- [ ] Unit tests passing and Documentation done

2024-11-04 14:49 UTC, rtkay123 commented on Research-Articles/Environment-Variables-Starndazation.md
> +- Unify env naming conventions accross all processors - maybe use the library to store config classes and validate provided config.
```suggestion
- Unify env naming conventions across all processors - maybe use the library to store config classes and validate provided config.
```

2024-11-04 14:49 UTC, rtkay123 commented on Research-Articles/Environment-Variables-Starndazation.md
> +    - Will requite some way to determine which processors require which config.
```suggestion
    - Will require some way to determine which processors require which config.
```

2024-11-04 14:50 UTC, rtkay123 commented on Research-Articles/Environment-Variables-Starndazation.md
> +- When validating environmental variables, use diffrent levels , ie - Error message when database is missing, but warning if nats env is missing.
```suggestion
- When validating environmental variables, use different levels, i.e - Error message when database is missing, but warning if NATS env is missing.
```

2024-11-04 14:53 UTC, rtkay123 reviewed
I left some suggestions

2024-11-05 06:11 UTC, rtkay123 approved these changes, later dismissed

2024-11-05 06:28 UTC, Sandy-at-Tazama requested changes
Please fix the name of the file - `standardization`

2024-11-05 07:57 UTC, Sandy-at-Tazama approved these changes, later dismissed

2024-11-05 10:19 UTC, Sandy-at-Tazama approved these changes

2024-11-05 12:32 UTC, merged