docs: product
frmscoe/docs pull request #42
Opened 2024-05-14 12:52 UTC by curlyreeve

2024-05-21 07:46 UTC, Justus-at-Tazama requested changes
Hi Laurence,

Please see and resolve review comments below. The first files in this PR turned out fine. About halfway through some of the files were going into the wrong folders and there is quite a bit of overlap between this PR and PR 41 - https://github.com/frmscoe/docs/pull/41/files

Please reconcile the files and locations against the indicated locations in the spreadsheet.

Please also note that the specific files:

- [configuration-management.md](https://github.com/frmscoe/docs/blob/dev/Product/configuration-management.md)
- [complete-example-of-a-network-map.md](https://github.com/frmscoe/docs/blob/dev/Product/complete-example-of-a-network-map.md)
- [complete-example-of-a-rule-processor-configuration.md](https://github.com/frmscoe/docs/blob/dev/Product/complete-example-of-a-rule-processor-configuration.md)
- [complete-example-of-a-typology-processor-configuration.md](https://github.com/frmscoe/docs/blob/dev/Product/complete-example-of-a-typology-processor-configuration.md)

Have all been migrated since the spreadsheet was created and last updated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Archive/Core-Processor/CADProc/Channel-Aggregation-And-Decisioning.md
This is not in scope for the migration, as per the spreadsheet.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Archive/Core-Processor/Data-Preparation/Entity-Resolution-Specification-for-Implementation.md
This should be in `docs/Knowledge-Articles/Entity-Resolution` as per the spreadsheet

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Channel-Router-And-Setup-Processor-CRSP.md
This should have been in the CRSP readme (complete) or not migrated as per the spreadsheet. This has already been migrated. This file is also duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Configuration-Management/Complete-Example-Of-A-Network-Map.md
This has already been migrated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Configuration-Management/Complete-Example-Of-A-Rule-Processor-Configuration.md
This has already been migrated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Configuration-Management/Complete-Example-Of-A-Typology-Processor-Configuration.md
This has already been migrated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Configuration-Management/Configuration-Management.md
This has already been migrated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Creating-and-Maintaining-Processors
This folder is required for:
04-Tazama-Rules-Life-Cycle
00-Introduction
01-Config-Driven-Design
02-Create-New-Rule-Processor
03-Create-New-Typology
04-Create-New-Channel
05-Create-New-Transaction

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/TADPROC_Response_v0.14_20211209.json
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Tazama-Rules-Life-Cycle.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

This file should be in the `docs/Product/Creating-and-Maintaining-Processors` folder.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/Transaction-Aggregation-And-Decisioning-Processor-Tadproc.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/configuration-management.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files as well as in this PR.

It has also already been migrated.

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/processor-results-propagation.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/rule-processor-overview-rule-config.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/rule-processor-overview.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/transaction-aggregation-and-decisioning-processor.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/transaction-monitoring-service-api.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-21 07:46 UTC, Justus-at-Tazama commented on Product/typology-processing.md
This file is duplicated in PR 41 - https://github.com/frmscoe/docs/pull/41/files

2024-05-24 08:26 UTC, RobReeveLexTego submitted a review, later dismissed
second block for archive.
Documents are now correctly named and in the correct location

2024-05-24 08:27 UTC, RobReeveLexTego commented on Product/Creating-and-Maintaining-Processors
will be added back in subsequent PR

2024-05-24 08:28 UTC, RobReeveLexTego approved these changes
renaming Tazama Platform to Tazama System

2024-05-24 17:37 UTC, RobReeveLexTego submitted a review, later dismissed
Changes to address conflicts

2024-05-25 07:37 UTC, Justus-at-Tazama approved these changes
Resolved merge conflicts caused by https://github.com/frmscoe/docs/pull/55/files

2024-05-25 07:37 UTC, merged